In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.9 MB 11.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.7/12.9 MB 11.0 MB/s eta 0:00:01
   --------------------- ------------------ 7.1/12.9 MB 11.2 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.9 MB 11.4 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.9 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 10.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np # 넘파이 np로 줄여서 쓴다. 예전에도 그랬고 지금도 그렇고...

# 넘파이 생성 방법

arr = np.array([1, 2, 3])
print(arr)
type(arr)



[1 2 3]


numpy.ndarray

In [ ]:
import numpy as np

# 2차원 배열 생성
arr = np.array([ [1, 2, 3], [4, 5, 6] ])
print(arr)

In [7]:
import numpy as np

# 3차원 배열 생성
arr = np.array([ [ [1], [2] ], [ [3], [4] ] ])
print(arr)

[[[1]
  [2]]

 [[3]
  [4]]]


In [11]:
# 기본값이 있는 배열 만들기
import numpy as np

arr = np.zeros(10, dtype=np.int32) # 최소값 -21억 ~ 21억까지
print(arr)

arr = np.zeros((2, 5)) # 데이터 타입을 정하지 않으면 기본형을 실수로 한다.
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
import numpy as np

arr = np.ones(10, dtype=np.int32)
print(arr)

arr = np.ones((3, 3))
print(arr)

[1 1 1 1 1 1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
import numpy as np

arr = np.arange(1, 10, 2) # 2만큼 스텝 상승
print(arr)

# 0 ~ 100 까지 100을 포함해서 5개로 나눈 값들이 출력
arr = np.linspace(0, 100, 3, dtype=np.int32)
print(arr)

[1 3 5 7 9]
[  0  50 100]


In [35]:
import numpy as np

arr = np.ones((3, 2))

print(arr.ndim) # 2 차원
print(arr.shape) # 3열 3행

a1 = np.array( [ 1, 2, 3, 4, 5 ])
a2 = np.array( [ [ 1, 2, 3, 4 ] , [ 1, 2, 3, 4 ] ] )
a3 = np.array( [ [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                     [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                     [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ] )

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a1.shape)
print(a2.shape)
print(a3.shape)

#(5, ) 1행 5열
#(2, 4) 2행 4열
#(3, 2, 3) 높이, 행, 열

2
(3, 2)
1
2
3
(5,)
(2, 4)
(3, 2, 3)


In [34]:
# 읽는 방법 = 인덱싱과 슬라이싱 지원

arr = np.array( [ 
    [ 0, 1, 2 ], 
    [ 3, 4, 5 ], 
    [ 6, 7, 8 ] 
    ] )

print(arr.shape)
print(arr[2, 2])



(3, 3)
8


In [36]:
# 값 수정
arr = np.array( [ 
    [ 0, 1, 2 ], 
    [ 3, 4, 5 ], 
    [ 6, 7, 8 ] 
    ] )

arr[1, 2] = 10
print(arr)

[[ 0  1  2]
 [ 3  4 10]
 [ 6  7  8]]


In [43]:
# 슬라이싱
arr = np.array( [ 
    [ 1, 2, 3, 4, 5 ],
    [ 6, 7, 8, 9, 10 ],
    [ 11, 12, 13, 14, 15] 
    ] )

print(arr.shape)
print(arr[1:3, 1:3]) # 1행 1열에서 부터 3 - 1열까지 출력
print(arr[1:2, :])


(3, 5)
[[ 7  8]
 [12 13]]
[[ 6  7  8  9 10]]


In [44]:
# bool 인덱싱
arr = np.array([0,1,2,3,4,5])
bool_arr = np.array([True, False, True, False, True, False])

print(arr[bool_arr])

[0 2 4]


In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

c = a + 5
print(c)

c = 5 * a
print(c)

c = 2 + 5 * b - a

print(c)

[5 7 9]
[6 7 8]
[ 5 10 15]
[21 25 29]


In [50]:
c = np.array([21, 25, 24])
c == 25



array([False,  True, False])

In [51]:
arr = np.array([ 
                    [ 0, 1, 2 ],
                    [ 3, 4, 5 ],
                    [ 6, 7, 8 ] 
               ])

print(arr.shape)
print(arr[2,2])
print(arr[0,0])

print(arr[-1,-1])
print(arr[-2,-2])
print(arr[-2,2])

(3, 3)
8
0
8
4
5
